language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t briankiernan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true briankiernan/react-test npm run test

after_success:
  - docker build -t briankiernan/multi-client ./client
  - docker build -t briankiernan/multi-nginx ./nginx
  - docker build -t briankiernan/multi-server ./server
  - docker build -t briankiernan/multi-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push built images to docker hub
  - docker push briankiernan/multi-client
  - docker push briankiernan/multi-nginx
  - docker push briankiernan/multi-server
  - docker push briankiernan/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'docker-react'
#   env: 'Dockerreact-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-339147933074'
#   bucket_path: 'docker-react'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
